name: tinkoff_invest
description: Tinkoff Invest OpenAPI SDK for Dart.
version: 0.1.0-dev.3
repository: https://github.com/greymag/tinkoff-invest-openapi-dart-sdk
issue_tracker: https://github.com/greymag/tinkoff-invest-openapi-dart-sdk/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.7.0
  dio: ^4.0.0
  list_ext: ^1.0.2
  meta: ^1.3.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  innim_lint: ^0.2.0
  mockito: ^5.0.8
  test: ^1.17.4
