name: tinkoff_invest
description: Tinkoff Invest OpenAPI SDK for Dart.
version: 0.1.0-dev
repository: https://github.com/greymag/tinkoff-invest-openapi-dart-sdk
issue_tracker: https://github.com/greymag/tinkoff-invest-openapi-dart-sdk/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  innim_lint: ^0.1.0
  test: ^1.16.8
